# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='品種名')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='場所名')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='購入日')),
                ('is_fan', models.BooleanField(verbose_name='リピート購入')),
                ('impression', models.TextField(verbose_name='感想')),
                ('remarks', models.CharField(max_length=255, verbose_name='備考')),
                ('cultivars', models.ManyToManyField(to='create_view.Cultivar', verbose_name='品種')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_view.Place', verbose_name='購入場所')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='時間帯名')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='time_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_view.TimeRange', verbose_name='時間帯'),
        ),
    ]
